### ISSUE TITLE
unable to rectify map

### ISSUE THREAD

**Issue by lklepner** [nypl-spacetime/nypl-warper#7] opened 2016-02-26 16:28 UTC
I've run into an issue with a map where rectifying fails every time -
http://maps.nypl.org/warper/maps/26776

**Comment by mgiraldo** [comment] 2016-03-01 17:51
we're working on issues with the map warper... seems to be a drive space issue

**Comment by mgiraldo** [comment] 2016-03-02 16:47
this should be working fine now. thanks!

**Comment by lklepner** [comment] 2016-03-02 17:01
Retrying it now.. but it seems to be hung

![screen shot 2016-03-02 at 12 01 16 pm](https://cloud.githubusercontent.com/assets/110027/13467959/867e987c-e06e-11e5-8c8d-c1cea9226ed2.png)

**Comment by lklepner** [comment] 2016-03-02 17:06
Yeah its hung

**Comment by mgiraldo** [comment] 2016-03-02 17:24
ok i will leave it open but it seems like the problem is that this map is massive and covers a huge area of new york/new jersey so the process will just take a while.

we have to let it run until it crashes (if it does) or successfully completes. this process is run in the background so it should not impede other regular tasks.

this does help us determine if more computing resources need to be added to the server.

**Comment by lklepner** [comment] 2016-03-02 17:30
sounds good. the map has three plates side by side. how do you recommend rectifying the second and third pieces?

**Comment by mgiraldo** [comment] 2016-03-02 17:38
there is a little-known feature in the map page called "create inset" which basically duplicates the map. from there you can crop the second plate and so on any subsequent plates:

<img width="751" alt="inset" src="https://cloud.githubusercontent.com/assets/133020/13469043/a0cb6156-e073-11e5-92fa-2e735629c9b2.png">

**Comment by lklepner** [comment] 2016-03-02 19:54
Thanks for the create inset lead. I'll try that when I get further along. 

Checking on the map I'm noticing that a problem I'd experienced earlier has resurfaced. Perhaps it has something to do with the large filesize? The rectifying process have resulted in a distortion where one corner of the map has been pulled to a seemingly arbitrary point. 

![screen shot 2016-03-02 at 2 53 11 pm](https://cloud.githubusercontent.com/assets/110027/13473259/994c96da-e086-11e5-95e8-ed2b35f2ed52.png)

![screen shot 2016-03-02 at 2 53 23 pm](https://cloud.githubusercontent.com/assets/110027/13473265/9d5ff3c0-e086-11e5-8d20-0d23927c1a65.png)

**Comment by mgiraldo** [comment] 2016-03-02 21:23
ok i'm gonna close this because rectification is working.

i think the problem was due to the control points. i added a couple of new control points and the rectification took very little time and produced nice results:

<img width="1085" alt="inset" src="https://cloud.githubusercontent.com/assets/133020/13475846/fc060804-e092-11e5-8b3b-6a35b240f924.png">

adding more points (or moving some of those i added somewhat hastily) will improve the result

**Closed by mgiraldo** 2016-03-02 21:23 UTC

**Comment by lklepner** [comment] 2016-03-02 21:39
Thanks for straightening things out. I'd thought 6 control points would be enough to get things into the general area. The skew to the far northwest was very unexpected. 

Thanks again for the help. I'll try fine tuning things further and creating insets.

**Comment by mgiraldo** [comment] 2016-03-02 22:03
i guess it depends on the map. in this case, it seems the math was
producing that weird loop over there... maybe because most points were
concentrated in a small area and then one or two far away... if the point
dispersion is a bit spread out then the math improves

**Comment by lklepner** [comment] 2016-03-03 12:48
Thanks for the tips. I thought I'd bang out the next inset this morning but I'm not seeing the Create Inset option you pointed out. 

![screen shot 2016-03-03 at 7 47 21 am](https://cloud.githubusercontent.com/assets/110027/13494772/5f45b88e-e114-11e5-82c5-bdc1d9db5588.png)

**Comment by mgiraldo** [comment] 2016-03-03 14:41
seems like it might be a feature for admins only so i went ahead and created two insets for you: [one](http://maps.nypl.org/warper/maps/29192), [two](http://maps.nypl.org/warper/maps/29193)

**Comment by lklepner** [comment] 2016-03-03 17:08
awesome - many thanks. i've rectified and cropped these insets.
